20210801

diff --git a/01-yad/lib/sparky-aptus-appcenter/bin/aptus-desktop-remove b/01-yad/lib/sparky-aptus-appcenter/bin/aptus-desktop-remove
--- a/01-yad/lib/sparky-aptus-appcenter/bin/aptus-desktop-remove
+++ b/01-yad/lib/sparky-aptus-appcenter/bin/aptus-desktop-remove
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# last update 2021/06/13 by pavroo
+# last update 2021/08/01 by pavroo
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-aptus-appcenter"
@@ -31,6 +31,18 @@ elif [ "`cat /etc/default/locale | grep LANG= | grep zh_CN`" != "" ]; then
 else
 . $DEFLOCDIR/en
 fi
+
+if [ -f /usr/bin/spterm ]; then
+	SPARKYXTERM="spterm -e"
+elif [ -f /usr/bin/sparky-xterm ]; then
+	SPARKYXTERM="sparky-xterm"
+elif [ -f /usr/bin/x-terminal-emulator ]; then
+	SPARKYXTERM="x-terminal-emulator -e"
+else
+	echo "x terminal emulator is missing... exiting..."
+	exit 1
+fi
+UNINSTALL="apt-get purge"
 
 # recive desktop name
 case $1 in
@@ -273,9 +285,9 @@ killall -9 yad
 cd /usr/lib/sparky-aptus-appcenter
 ./aptus-appcenter error01
 exit 0		
-fi
 
-else		
+else
+killall -9 yad	
 $SPARKYXTERM "$UNINSTALL $REMPACKS"
 
 if [ -f /usr/share/doc/sparky-desktop-$PACKAGE/copyright ]; then
